### ISSUE TITLE
note: /usr/bin/ld: cannot find -lflutter_engine

### ISSUE THREAD

**Issue by boltomli** [flutter-rs/flutter-app-template#5]
I followed the README but hit the error. Cannot find proper way in document of both repos. Eager to try this for a flutter project, could you please help?

**Comment by dvc94ch** [comment]
Are you using cargo-flutter to build? cargo-flutter should download the correct engine and place it in your `target/{arch}/{profile}/deps` folder where it'll be found by the linker

**Comment by boltomli** [comment]
Thanks for the hint. `cargo install cargo-flutter` works. Also, flutter has to be in stable channel.
