### ISSUE TITLE
What's the purpose of the project?

### ISSUE THREAD

**Issue by ProgrammingLife** [flutter-rs/flutter-app-template#8]
I'm looking at the source code here: https://github.com/flutter-rs/flutter-app-template/blob/master/lib/main.dart and I don't understand the main goal of flutter-rs project. That code is just a common flutter code what does flutter-rs should do?
Sorry I didn't find any readme files or so.

**Comment by zicklag** [comment]
This isn't an unreasonable question, is there a reason this was closed @dvc94ch ? As far as I understand so far, flutter-rs allows you to embed and run flutter UIs in Rust applications. So unlike normal flutter, Rust is actually creating the window and such. On Linux I think this comes with the advantage of not depending on Gtk like flutter does by default on linux.

As far as allowing you to write Rust code that can be used in a Flutter UI, I haven't seen a real example of that yet, but I'm assuming that `flutter-rs` is going to provide some sort of functionality around that.

**Comment by zicklag** [comment]
Ah, here is an example of a flutter plugin that hooks in Rust functionality with the flutter UI: 

https://github.com/flutter-rs/flutter-video-plugin

The magic is here:

https://github.com/flutter-rs/flutter-video-plugin/blob/99b6133b8cdee38432d45c762c12318818ff1ad7/src/plugin.rs#L48

**Comment by dvc94ch** [comment]
I'd suggest looking into iced if you're interested in ui for rust applications.
